[package]
categories = [
  "web-programming::http-server",
  "web-programming",
  "database",
  "asynchronous",
]
description = "🪪 Session-based user authentication for Axum."
documentation = "https://docs.rs/axum-login"
edition = "2021"
homepage = "https://github.com/maxcountryman/axum-login"
keywords = ["sessions", "authentication", "authorization", "login", "axum"]
license = "MIT"
name = "axum-login"
repository = "https://github.com/maxcountryman/axum-login"
version = "0.5.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
mssql = ["sqlx/mssql"]
mysql = ["sqlx/mysql"]
postgres = ["sqlx/postgres"]
rusqlite = ["dep:rusqlite", "dep:tokio-rusqlite"]
sqlite = ["sqlx/sqlite"]
sqlx = ["sqlx/runtime-tokio-rustls"]

[dependencies]
async-trait = "0.1.57"
axum = "0.6"
axum-sessions = "0.5"
base64 = "0.13"
dyn-clone = "1"
futures = "0.3"
percent-encoding = "2.2"
ring = "0.16"
rusqlite = {version = ">=0.27.0", optional = true}
secrecy = "0.8"
serde = "1"
serde_json = "1"
sqlx = {version = ">=0.6", optional = true}
tokio = {version = "1.20", features = ["sync"]}
tokio-rusqlite = {version = ">=0.2.0", optional = true}
tower = "0.4"
tower-http = {version = "0.4", features = ["auth"]}
tracing = "0.1"

[dev-dependencies]
http = "0.2"
hyper = "0.14"

[dev-dependencies.rand]
features = ["min_const_gen"]
version = "0.8"

[dev-dependencies.tokio]
default-features = false
features = ["macros", "rt-multi-thread"]
version = "1.20"
